version: '3.8'

services:
  bot-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Wave_bot
    ports:
      - 3999:3999
    restart: always
    networks:
      - home
networks:
  home:
    driver: bridge