version: '3.8'

services:
  bot-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Wave_bot
    restart: always
    # Настройки для graceful shutdown
    stop_signal: SIGTERM
    stop_grace_period: 30s
    networks:
      - home
networks:
  home:
    driver: bridge